** Solutions to Nathanson's Elementary Methods in Number Theory

Version: 0.1 (in preparation)

Get the PDF [here](NathansonSolutions.pdf)

*** About the Book

This is a solution manual (in preparation) for the popular textbook [[https://link.springer.com/book/10.1007/b98870#:~:text=Elementary%20Methods%20in%20Number%20Theory%20begins%20with%20%22a%20first%20course,%2C%20prime%20numbers%2C%20and%20congruences][Elementary Methods in Number Theory]] by Melvyn B. Nathanson.

*** History

This solution manual is an indirect product of my (pre) summer work at ISI (Delhi) in 2022. Indeed, I solved these problems in preparation for it. I thoroughly enjoyed solving these problems but I quickly realized typesetting them in TeX/LaTex and putting them on GitHub would add more value to them. This was how this repo came into being.

*** Present and Beyond

As of now, it only contains solutions to the first three chapters. Solutions to chapter 4 and 5 are currently in preparation. 

I plan to cover more chapters and add more solutions in near future.

*** Bugs

There could be typos and errors. I fix them whenever I see them. Report them if you happen to find them. I would be pleased.

Reach me (or report bugs) at ronhuidrom@gmail.com.
